### ISSUE TITLE
Sink States

### ISSUE THREAD

**Issue by willow-iam** [milanboers/rurel#12]
I want to use this with an MDP that has sink states. That is, states with reward and no possible actions. Can I do so with this, and if so, how?

**Comment by milanboers** [comment]
Hey! I think this is similar to https://github.com/milanboers/rurel/issues/8 . I put some psuedocode on there back then that may be helpful. Let me know if that helps!

**Comment by willow-iam** [comment]
That ought to be part of the crate, rather than buried in the issues.

**Comment by milanboers** [comment]
Closed by PR #15
