### ISSUE TITLE
Train by individual steps

### ISSUE THREAD

**Issue by tqwewe** [milanboers/rurel#13]
Is it possible to train a single step at a time, so I can have it run within something like a bevy system?

It seems like the current train method is usually done with a certain amount of iterations, but perhaps a function `step` or `train_step` would be convenient?

**Comment by milanboers** [comment]
You could use `FixedIterations::new(0)` as your termination strategy.

You can repeatedly call `AgentTrainer.train` and it will continue with the currently learned values.
