### ISSUE TITLE
Usage for future values?

### ISSUE THREAD

**Issue by dakom** [milanboers/rurel#2]
Question... can this library be used for something like Pong - i.e. where the reward isn't known right away, but rather becomes eventually known and somehow backpropogated?

I guess the reward _could_ sortof be immediately known, by checking y-distance from the ball.. but that's not a huge win over just manually making it chase the ball. It'd be nicer to have the AI figure out other things - like trying to hit the ball such that it makes the opponent chase it a longer distance.

Sorry for the naive question - I haven't jumped into ML yet and I'm just tinkering around with a webassembly pong thing and thought this library might be a nice way to drive the AI :)

**Comment by milanboers** [comment]
The reward does not need to be immediately known. You could assign a reward to only states where the ball is hitting the bat, and after sufficient training it should have figured out an expected reward for all other states as well.
I think the main difficulty here is that you don't know what your opponent is going to do, so you cannot deterministically compute the next state from the current state. You could make it random, but that's not very realistic. Or have it train against another AI.
