### ISSUE TITLE
Saving model to disk

### ISSUE THREAD

**Issue by mageowl** [milanboers/rurel#20]
Is it possible to save a DQNAgentTrainer to a file? The `.save()` method from dfdx on `export_learned_values` seems to not be able to be used because it doesn't implement TensorCollection.

**Comment by milanboers** [comment]
Hi! The `QNetworkDevice` [is a tuple of](https://github.com/milanboers/rurel/blob/master/src/dqn.rs#L21) `nn:modules::Linear`. Perhaps [you can use](https://docs.rs/dfdx/latest/x86_64-pc-windows-msvc/dfdx/nn/modules/struct.Linear.html#method.save) `.save` on the individual elements.

**Comment by mageowl** [comment]
Thank you!
